version: '3.8'

services:
  lis-database:
    image: mariadb:lts
    container_name: lis-database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - 3307:3307
    volumes:
      - mysql-data:/var/lib/mysql

  lis-backend:
    depends_on:
      - lis-database
    container_name: lis-backend
    build:
      context: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $DEBUG_LOCAL_PORT:$DEBUG_DOCKER_PORT
    environment:
      - SERVER_PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  lis-adminer:
    image: adminer
    container_name: lis-adminer
    # depends_on:
    #   - lis-database
    ports:
      - 8082:8080

volumes:
  mysql-data:
